# Generated by Django 6.0.3 on 2026-03-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=255)),
                ('skills', models.CharField(max_length=255)),
                ('current_role', models.CharField(max_length=255)),
                ('proficiency_level', models.CharField(choices=[('Entry', 'Entry'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Candidates',
                'ordering': ['candidate_name'],
            },
        ),
    ]
