# Generated by Django 6.0.3 on 2026-03-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentPool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='candidate',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('Internal', 'Internal'), ('External', 'External')], max_length=50),
        ),
        migrations.AddField(
            model_name='candidate',
            name='grade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='candidate',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='skill_vectors',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='proficiency_level',
            field=models.CharField(blank=True, choices=[('Entry', 'Entry'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='skills',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('candidate_name', 'email')},
        ),
    ]
