# Generated by Django 6.0.3 on 2026-03-12 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentPool', '0002_candidate_email_candidate_employment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='skill_vectors',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
